//@ sourceMappingURL=connect.test.map
// Generated by CoffeeScript 1.6.1
(function() {
  var assert, async, wongo,
    __hasProp = {}.hasOwnProperty;

  assert = require('assert');

  async = require('async');

  wongo = require('../lib/wongo');

  describe('Wongo.connect()', function() {
    it('should connect to the database', function(done) {
      wongo.connect(process.env.DB_URL);
      return done();
    });
    return it('should clear every registered schema', function(done) {
      var _type, _types;
      _types = (function() {
        var _ref, _results;
        _ref = wongo.schemas;
        _results = [];
        for (_type in _ref) {
          if (!__hasProp.call(_ref, _type)) continue;
          _results.push(_type);
        }
        return _results;
      })();
      return async.each(_types, function(_type, nextInLoop) {
        return wongo.clear(_type, nextInLoop);
      }, done);
    });
  });

}).call(this);
