//@ sourceMappingURL=schema.test.map
// Generated by CoffeeScript 1.6.1
(function() {
  var assert, wongo;

  assert = require('assert');

  wongo = require('../lib/wongo');

  describe('Wongo Schema', function() {
    it('should change String into type.String', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: String
        }
      });
      assert.equal(schema.fields.strictType.type, String);
      return done();
    });
    it('should keep type String', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: {
            type: String
          }
        }
      });
      assert.equal(schema.fields.strictType.type, String);
      return done();
    });
    it('should change Number into type.Number', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: Number
        }
      });
      assert.equal(schema.fields.strictType.type, Number);
      return done();
    });
    it('should keep type Number', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: {
            type: Number
          }
        }
      });
      assert.equal(schema.fields.strictType.type, Number);
      return done();
    });
    it('should change Date into type.Date', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: Date
        }
      });
      assert.equal(schema.fields.strictType.type, Date);
      return done();
    });
    it('should keep type Date', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: {
            type: Date
          }
        }
      });
      assert.equal(schema.fields.strictType.type, Date);
      return done();
    });
    it('should change Boolean into type.Boolean', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: Boolean
        }
      });
      assert.equal(schema.fields.strictType.type, Boolean);
      return done();
    });
    return it('should keep type Boolean', function(done) {
      var schema;
      schema = wongo.schema('MockSchema', {
        fields: {
          strictType: {
            type: Boolean
          }
        }
      });
      assert.equal(schema.fields.strictType.type, Boolean);
      return done();
    });
  });

}).call(this);
