//@ sourceMappingURL=applyDefaults.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _,
    __hasProp = {}.hasOwnProperty;

  _ = require('underscore');

  module.exports = function(document, schema, callback) {
    var applyDefaults;
    applyDefaults = function(doc, fields) {
      var item, meta, prop, _ref, _ref1, _ref2, _results;
      _ref = fields != null ? fields : {};
      _results = [];
      for (prop in _ref) {
        if (!__hasProp.call(_ref, prop)) continue;
        meta = _ref[prop];
        if (_.isUndefined(meta)) {
          continue;
        }
        if (_.isArray(meta) && ((_ref1 = meta[0]) != null ? _ref1.type : void 0)) {
          _results.push((_ref2 = doc[prop]) != null ? _ref2 : doc[prop] = meta[0]["default"]);
        } else if (_.isArray(meta)) {
          _results.push((function() {
            var _i, _len, _ref3, _ref4, _results1;
            _ref4 = (_ref3 = doc[prop]) != null ? _ref3 : [];
            _results1 = [];
            for (_i = 0, _len = _ref4.length; _i < _len; _i++) {
              item = _ref4[_i];
              _results1.push(applyDefaults(item, meta[0]));
            }
            return _results1;
          })());
        } else if (!(meta != null ? meta.type : void 0)) {
          _results.push(applyDefaults(doc[prop], meta));
        } else {
          if (_.isUndefined(doc[prop]) && !_.isUndefined(meta["default"])) {
            _results.push(doc[prop] = meta["default"]);
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };
    applyDefaults(document, schema.fields);
    return callback();
  };

}).call(this);
