//@ sourceMappingURL=applyDefaults.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _,
    __hasProp = {}.hasOwnProperty;

  _ = require('underscore');

  module.exports = function(document, schema, callback) {
    var applyDefaults;
    applyDefaults = function(document, fields) {
      var item, meta, prop, val, _ref, _ref1, _ref2, _ref3, _results;
      _ref = document != null ? document : {};
      _results = [];
      for (prop in _ref) {
        if (!__hasProp.call(_ref, prop)) continue;
        val = _ref[prop];
        if (prop === '_id') {
          continue;
        }
        meta = fields[prop];
        if (_.isUndefined(meta)) {
          continue;
        }
        if (_.isArray(meta) && ((_ref1 = meta[0]) != null ? _ref1.type : void 0)) {
          if (_.isUndefined(val)) {
            _results.push((_ref2 = document[prop]) != null ? _ref2 : document[prop] = meta[0]["default"]);
          } else {
            _results.push(void 0);
          }
        } else if (_.isArray(meta)) {
          _results.push((function() {
            var _i, _len, _ref3, _results1;
            _ref3 = val != null ? val : [];
            _results1 = [];
            for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
              item = _ref3[_i];
              _results1.push(applyDefaults(item, meta[0]));
            }
            return _results1;
          })());
        } else if (!(meta != null ? meta.type : void 0)) {
          _results.push(applyDefaults(val, meta));
        } else {
          if (_.isUndefined(val)) {
            _results.push((_ref3 = document[prop]) != null ? _ref3 : document[prop] = meta["default"]);
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };
    applyDefaults(document, schema.fields);
    return callback();
  };

}).call(this);
