//@ sourceMappingURL=prune.map
// Generated by CoffeeScript 1.6.1
(function() {
  var _,
    __hasProp = {}.hasOwnProperty;

  _ = require('underscore');

  module.exports = function(document, schema, callback) {
    var prune;
    prune = function(document, fields) {
      var item, meta, prop, val, _ref, _results;
      _ref = document != null ? document : {};
      _results = [];
      for (prop in _ref) {
        if (!__hasProp.call(_ref, prop)) continue;
        val = _ref[prop];
        if (prop === '_id') {
          continue;
        }
        meta = fields[prop];
        if (!meta) {
          _results.push(delete document[prop]);
        } else if (_.isArray(meta)) {
          _results.push((function() {
            var _i, _len, _ref1, _results1;
            _ref1 = val != null ? val : [];
            _results1 = [];
            for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
              item = _ref1[_i];
              if (_.isObject(item)) {
                _results1.push(prune(item, meta[0]));
              } else {
                _results1.push(void 0);
              }
            }
            return _results1;
          })());
        } else if (_.isObject(val)) {
          _results.push(prune(val, meta));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    prune(document, schema.fields);
    return callback();
  };

}).call(this);
