//@ sourceMappingURL=wongo.map
// Generated by CoffeeScript 1.6.1
(function() {
  var crud, hooks, modeler, mongo, options;

  exports.mongodb = require('mongodb');

  exports.ObjectID = mongodb.ObjectID;

  mongo = require(__dirname + '/mongo');

  exports.connect = mongo.connect;

  exports.db = mongo.db;

  exports.ifConnected = mongo.ifConnected;

  exports.collection = mongo.collection;

  options = require(__dirname + '/options');

  exports.options = options;

  modeler = require(__dirname + '/modeler');

  exports.schema = modeler.schema;

  exports.schemas = modeler.schemas;

  hooks = require(__dirname + '/hooks');

  exports.validate = hooks.validate;

  exports.prune = hooks.prune;

  exports.plugins = require(__dirname + '/plugins');

  crud = require(__dirname + '/crud');

  exports.save = crud.save;

  exports.remove = crud.remove;

  exports.clear = crud.clear;

  exports.find = crud.find;

  exports.findOne = crud.findOne;

  exports.findById = crud.findById;

  exports.findByIds = crud.findByIds;

}).call(this);
